Repository the-collab-lab/tcl-73-smart-shopping-list, pull requests merged in 2024-02, with the labels that each got.

#18 Fix navigation links - replace anchor links with NavLinks
  src/views/Layout.jsx
Labels: accessibility, enhancement

#20 Issue 5. Add Items to list
  src/App.jsx
  src/api/firebase.js
  src/views/ManageList.jsx
Labels: enhancement

#21 Set up shopping list
  src/api/firebase.js
  src/views/Home.jsx
Labels: accessibility, enhancement, help wanted

#23 Add shopping list search function
  src/views/List.jsx
Labels: enhancement
