Repository the-collab-lab/tcl-73-smart-shopping-list, pull requests merged in 2024-03, with the labels that each got.

#25 Item checkbox functionality
  src/App.jsx
  src/api/firebase.js
  src/components/ListItem.jsx
  src/utils/dates.js
  src/views/List.jsx
Labels: accessibility, enhancement

#24 Add Welcoming Prompt for User's First List Item
  src/views/List.jsx
Labels: accessibility, enhancement

#27 Calculate next purchase date for an item.
  package-lock.json
  package.json
  src/api/firebase.js
  src/components/ListItem.jsx
  src/utils/dates.js
Labels: enhancement, refactoring

#26 Input validations for adding new items
  src/App.jsx
  src/components/AddItem.jsx
  src/utils/itemValidator.js
  src/views/ManageList.jsx
  tests/itemValidator.test.js
Labels: accessibility, enhancement

#29 Add item sorting functionality.
  src/api/firebase.js
  src/components/ListItem.css
  src/components/ListItem.jsx
  src/utils/comparePurchaseUrgency.js
  src/utils/dates.js
  src/views/List.jsx
Labels: bug fix, enhancement, refactoring

#28 Create Delete Item button
  PROJECT-BRIEF.md
  package-lock.json
  package.json
  src/api/firebase.js
  src/components/ListItem.jsx
  tests/deleteItem.test.js
Labels: accessibility, enhancement
